### ISSUE TITLE
Encounter error when run cirr test

### ISSUE THREAD

**Issue by BUAADreamer** [ABaldrati/CLIP4Cir#9]
Thanks for such a great job!
In README, `--projection-dim 4096 --hidden-dim 8192` are  used for cirr test, however, when I run the code, I encounter error bolow
So the right way is `--projection-dim 2560 --hidden-dim 5120` as the same as the validate?
```
Traceback (most recent call last):
  File "src/cirr_test_submission.py", line 221, in <module>
    main()
  File "src/cirr_test_submission.py", line 211, in main
    combiner.load_state_dict(saved_state_dict["Combiner"])
  File "/home/LAB/fengzc/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Combiner:
        size mismatch for text_projection_layer.weight: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([4096, 640]).
        size mismatch for text_projection_layer.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([4096]).
        size mismatch for image_projection_layer.weight: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([4096, 640]).
        size mismatch for image_projection_layer.bias: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([4096]).
        size mismatch for combiner_layer.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([8192, 8192]).
        size mismatch for combiner_layer.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([8192]).
        size mismatch for output_layer.weight: copying a param with shape torch.Size([640, 5120]) from checkpoint, the shape in current model is torch.Size([640, 8192]).
        size mismatch for dynamic_scalar.0.weight: copying a param with shape torch.Size([5120, 5120]) from checkpoint, the shape in current model is torch.Size([8192, 8192]).
        size mismatch for dynamic_scalar.0.bias: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([8192]).
        size mismatch for dynamic_scalar.3.weight: copying a param with shape torch.Size([1, 5120]) from checkpoint, the shape in current model is torch.Size([1, 8192]).
```

**Comment by ABaldrati** [comment]
Hi!
Thanks for your interest in our work!

Yes you are right, there is a typo in the README
Thank you for the report
